#!/usr/bin/env ruby

$: << File.expand_path(File.dirname(__FILE__) + '/../lib')

require 'allele_image'

if ARGV.size < 1
  STDERR.puts '.gbk file and optional cassette flag only please'
  exit 1
end

file = ARGV.first
cassetteonly = ARGV[1]
allele_image = AlleleImage::Image.new(file, cassetteonly == 'true')
image = file.gsub(/\.gbk$/, '.png')
allele_image.render.write(image)
